server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/spring-template?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: prod_user
    password: prod_pass
  data:
    redis:
      host: prod-redis-host
      port: 6379
      password: prod_pass
      database: 0
      lettuce:
        pool:
          max-active: 20
          max-wait: 1000
          max-idle: 10
          min-idle: 5

knife4j:
  basic:
    enable: false
